import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';

export type RentPaymentDocument = RentPayment & Document;

/**
 * Rent Payment Schema
 * Auto-generated by system, cannot be manually created or deleted
 * Only payment status fields can be updated
 */
@Schema({ timestamps: true })
export class RentPayment {
  @Prop({ required: true, type: Types.ObjectId, ref: 'Tenant' })
  tenantId: Types.ObjectId;

  @Prop({ required: true, type: Types.ObjectId, ref: 'Resident' })
  residentId: Types.ObjectId;

  @Prop({ type: Types.ObjectId, ref: 'Bed' })
  bedId?: Types.ObjectId;

  @Prop({ required: true })
  month: string; // Format: "YYYY-MM"

  @Prop({ required: true })
  amountDue: number; // Monthly rent amount

  @Prop({ default: 0 })
  amountPaid: number; // Amount paid so far

  @Prop({ required: true })
  dueDate: Date; // Payment due date

  @Prop()
  paidDate?: Date; // When payment was marked as paid

  @Prop()
  paymentMode?: string; // Cash, UPI, Bank Transfer

  @Prop({
    required: true,
    enum: ['UPCOMING', 'DUE', 'PARTIAL', 'PAID', 'OVERDUE'],
    default: 'DUE',
  })
  status: string;

  @Prop()
  notes?: string;

  @Prop({ type: [String], default: [] })
  tags?: string[]; // Custom tags for payments

  @Prop({ default: false })
  isAutoGenerated: boolean; // Always true for rent payments

  @Prop()
  createdAt?: Date;

  @Prop()
  updatedAt?: Date;
}

export const RentPaymentSchema = SchemaFactory.createForClass(RentPayment);
// Unique constraint for monthly rent payments
RentPaymentSchema.index({ tenantId: 1, residentId: 1, month: 1 }, { unique: true });
// Due date and status queries (for dashboard and overdue checks)
RentPaymentSchema.index({ tenantId: 1, dueDate: 1, status: 1 });
RentPaymentSchema.index({ tenantId: 1, status: 1 });
// Bed-based queries (bed is source of truth)
RentPaymentSchema.index({ tenantId: 1, bedId: 1 });
RentPaymentSchema.index({ tenantId: 1, bedId: 1, status: 1 });
// Month-based queries
RentPaymentSchema.index({ tenantId: 1, month: 1 });
RentPaymentSchema.index({ tenantId: 1, month: 1, status: 1 });
// Resident payment history
RentPaymentSchema.index({ tenantId: 1, residentId: 1, status: 1 });
// Overdue payment queries (common dashboard query)
RentPaymentSchema.index({ tenantId: 1, dueDate: 1, status: 1, month: -1 });
// Tags filtering
RentPaymentSchema.index({ tenantId: 1, tags: 1 });