import {
  Controller,
  Get,
  Post,
  Body,
  Patch,
  Param,
  Delete,
  Query,
  UseGuards,
  ForbiddenException,
  BadRequestException,
} from '@nestjs/common';
import { PaymentsService } from './payments.service';
import { CreatePaymentDto } from './dto/create-payment.dto';
import { UpdatePaymentDto } from './dto/update-payment.dto';
import { JwtAuthGuard } from '../common/guards/jwt-auth.guard';
import { TenantId } from '../common/decorators/tenant.decorator';

@Controller('payments')
@UseGuards(JwtAuthGuard)
export class PaymentsController {
  constructor(private readonly paymentsService: PaymentsService) {}

  @Post()
  create(@Body() createPaymentDto: CreatePaymentDto, @TenantId() tenantId: string): Promise<any> {
    // Prevent manual creation of rent payments
    if (createPaymentDto.paymentType === 'rent' || createPaymentDto.month) {
      throw new ForbiddenException(
        'Rent payments are auto-generated by the system. Use /payments/rent endpoints to update payment status.',
      );
    }
    return this.paymentsService.create(createPaymentDto, tenantId);
  }

  @Get()
  findAll(@Query('residentId') residentId: string, @TenantId() tenantId: string) {
    return this.paymentsService.findAll(tenantId, residentId);
  }

  @Get('summary')
  getSummary(
    @Query('startDate') startDate: string,
    @Query('endDate') endDate: string,
    @TenantId() tenantId: string,
  ) {
    return this.paymentsService.getSummary(
      tenantId,
      startDate ? new Date(startDate) : undefined,
      endDate ? new Date(endDate) : undefined,
    );
  }

  @Get('pending')
  getPendingPayments(@TenantId() tenantId: string) {
    return this.paymentsService.getPendingPayments(tenantId);
  }

  @Get('overdue')
  getOverduePayments(@TenantId() tenantId: string) {
    return this.paymentsService.getOverduePayments(tenantId);
  }

  @Get('stats')
  getPaymentStats(@TenantId() tenantId: string) {
    return this.paymentsService.getPaymentStats(tenantId);
  }

  // IMPORTANT: This route must come AFTER all specific routes to avoid conflicts
  // Routes like /payments/rent, /payments/extra, etc. are handled by their respective controllers
  @Get(':id')
  findOne(@Param('id') id: string, @TenantId() tenantId: string): Promise<any> {
    // Check if the id is a route keyword (rent, extra, etc.)
    const routeKeywords = ['rent', 'extra', 'security-deposits'];
    if (routeKeywords.includes(id)) {
      throw new BadRequestException(`Invalid payment ID. Use /payments/${id} for ${id} payments.`);
    }
    return this.paymentsService.findOne(id, tenantId);
  }

  @Patch(':id')
  update(
    @Param('id') id: string,
    @Body() updatePaymentDto: UpdatePaymentDto,
    @TenantId() tenantId: string,
  ): Promise<any> {
    return this.paymentsService.update(id, updatePaymentDto, tenantId);
  }

  @Delete(':id')
  remove(@Param('id') id: string, @TenantId() tenantId: string) {
    return this.paymentsService.remove(id, tenantId);
  }
}
